version: '{build}'
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
nuget:
  disable_publish_on_pr: true
build_script:
- ps: .\Build.ps1
artifacts:
- path: .\Protacon.NetCore.WebApi.ApiKeyAuth\artifacts\**\*.nupkg
  name: NuGet
deploy:
- provider: NuGet
  name: production
  api_key:
    secure: ZQ7SW5khBueQZBzRxUkZ9uRSrCQWEYyjY5119+8GO9YX5Sy4/7wVv4sSoTCfo7q6
  on:
    branch: master
    appveyor_repo_tag: true